name: Deploy
run-name: ${{ github.actor }} started deploy on Yandex Cloud Function

on:
  push:
    branches:
      - master
    tags:

jobs:
  # TODO: check version change job
  deploy-to-yc:
    if: startsWith(github.ref, 'refs/tags/') && startsWith(github.ref_name, 'v')

    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Create requests.txt
      run: echo "counter_bot @ git+https://github.com/KH9IZ/counter_bot.git@${{github.ref_name}}" > requirements.txt
    - name: Deploy function
      id: sls-func
      uses: yc-actions/yc-sls-function@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: 'b1gjoe0i1p33c41023gp'
        function-name: 'my-first-cloud-function'
        runtime: 'python311'
        memory: '128Mb'
        entrypoint: 'counter_bot.cloud_function'
        include: requirements.txt
        environment: TOKEN=${{ secrets.TOKEN }}
